#!/usr/bin/env python3
"""Build configs/models.yaml — the TellTail model registry.

This documents exactly how the registry was derived: it extracts the
``retrieval_task`` string and ``MODEL_INSTRUCTIONS`` dict verbatim from the
original experiment script, joins them with the alias->hf_id map, and emits a
YAML file with the model-specific prefixes preserved BYTE-EXACT (trailing
spaces and embedded newlines are significant for retrieval quality).

The ``--src`` directory is expected to contain:
  - generate_rankings_byK.py   (defines retrieval_task + MODEL_INSTRUCTIONS)
  - model_map.json             ({alias: hf_id})

Usage:
    python tools/build_models_yaml.py --src /path/to/source_dir \
        --out configs/models.yaml
"""
import argparse
import json
import re
from pathlib import Path

# The 19 models the attacker holds in its candidate set S (paper §V-A).
CANDIDATES = {
    "qwen-0.6b", "qwen-4b", "e5-small", "e5-base", "e5-large",
    "gte-modernbert", "gte-large-v1.5", "gte-base-v1.5", "gte-multi",
    "nomic-modernbert", "nomic-v1.5", "gtr-t5-base", "minilm-l6",
    "minilm-l12", "mpnet", "snowflake-v2", "gemma-300m", "bge-base",
    "openai-3-small",
}


def extract_instructions(src_py: Path) -> dict:
    """Exec only the retrieval_task + MODEL_INSTRUCTIONS slice (no heavy deps)."""
    text = src_py.read_text(encoding="utf-8")
    m = re.search(r"^retrieval_task = .*?^MODEL_INSTRUCTIONS = \{.*?^\}",
                  text, re.S | re.M)
    if not m:
        raise SystemExit(f"could not locate MODEL_INSTRUCTIONS in {src_py}")
    ns: dict = {}
    exec(compile(m.group(0), str(src_py), "exec"), ns)
    return ns["MODEL_INSTRUCTIONS"]


def dq(s: str) -> str:
    """Render a YAML double-quoted scalar that round-trips exactly."""
    s = s.replace("\\", "\\\\").replace('"', '\\"')
    s = s.replace("\n", "\\n").replace("\t", "\\t").replace("\r", "\\r")
    return f'"{s}"'


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", required=True, type=Path,
                    help="Dir with generate_rankings_byK.py and model_map.json")
    ap.add_argument("--out", required=True, type=Path,
                    help="Output path for models.yaml")
    args = ap.parse_args()

    instr = extract_instructions(args.src / "generate_rankings_byK.py")
    model_map = json.loads(
        (args.src / "model_map.json").read_text(encoding="utf-8"))

    lines = [
        "# TellTail model registry (53 models; 19 candidates).",
        "# Auto-generated by tools/build_models_yaml.py from the original",
        "# MODEL_INSTRUCTIONS + model_map.json. Do not hand-edit.",
        "# Prefixes are byte-exact: trailing spaces and \\n are intentional.",
        "models:",
    ]
    n_cand = 0
    for alias, hf_id in model_map.items():
        ins = instr.get(hf_id, {})
        is_cand = alias in CANDIDATES
        n_cand += int(is_cand)
        backend = "openai" if hf_id.startswith("openai/") else "sentence_transformers"
        lines += [
            f"  - alias: {dq(alias)}",
            f"    hf_id: {dq(hf_id)}",
            f"    query_prefix: {dq(ins.get('query_prefix', ''))}",
            f"    passage_prefix: {dq(ins.get('passage_prefix', ''))}",
            f"    candidate: {'true' if is_cand else 'false'}",
            f"    backend: {backend}",
        ]

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {args.out}: {len(model_map)} models, {n_cand} candidates")

    assert len(model_map) == 53, f"expected 53 models, got {len(model_map)}"
    assert n_cand == 19, f"expected 19 candidates, got {n_cand}"
    missing = CANDIDATES - set(model_map)
    assert not missing, f"candidate aliases missing from model_map: {missing}"
    print("OK: 53 models, 19 candidates, all candidate aliases present")


if __name__ == "__main__":
    main()
